version: '3.7'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  allergies_service:
    build: ./allergy_service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/db
    depends_on:
      db:
        condition: service_healthy

  vital_signs_service:
    build: ./vital_service
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
