version: '3.8'

services:
  mongo:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  routine-service:
    build:
      context: .
    container_name: routine-service
    environment:
      - DATABASE_URI=mongodb://mongo:27017/FYP
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  routine-service-test:
    build:
      context: .
    container_name: routine-service-test
    environment:
      - DATABASE_URI=mongodb://mongo:27017/FYP
      - PORT=3001
    command: ["npm", "test"]
    depends_on:
      - mongo

volumes:
  mongo-data:
